### ISSUE TITLE
The point example in readme.md does not work

### ISSUE THREAD

**Issue by peterbjorgensen** [mariogeiger/se3cnn#43]
When running the example in the `readme.md` I get the following error.
I think it is caused because the example script was written before the batch dimension was introduced?
```
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
compute... save... done
Traceback (most recent call last):
  File "example.py", line 29, in <module>
    features = conv(features, geometry)
  File "/usr/lib/python3.7/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/peter/.local/lib/python3.7/site-packages/se3cnn/point/operations.py", line 16, in forward
    assert features.size()[:2] == geometry.size()[:2], "features size ({}) and geometry size ({}) should match".format(features.size(), geometry.size())
AssertionError: features size (torch.Size([1, 3])) and geometry size (torch.Size([3, 3])) should match
```

**Comment by mariogeiger** [comment]
Thanks
