### ISSUE TITLE
No such file or directory: 'cache/trans_Q/1.pkl.gz'

### ISSUE THREAD

**Issue by dragonbook** [mariogeiger/se3cnn#5]
Hi, When I run example code in README.md(or examples in se3cnn/examples/example.py, or 
se3cnn/tests/convolution_tests.py), some errors occured like this:

---------------------------------
(pytorch-0.4.1) yalong@pc:~/yalong/project/groupy-cnn/se3cnn$ python
Python 3.6.4 |Anaconda, Inc.| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> from se3cnn import SE3Convolution
>>> 
>>> size = 32  # space size
>>> 
>>> scalar_field = torch.randn(1, 1, size, size, size)  # [batch, _, x, y, z]
>>> 
>>> Rs_in = [(1, 0)]  # 1 scalar field
>>> Rs_out = [(1, 1)]  # 1 vector field
>>> conv = SE3Convolution(Rs_in, Rs_out, size=5)
compute 1.pkl.gz... save 1.pkl.gz... done
compute 1.pkl.gz... Traceback (most recent call last):
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/util/cache_file.py", line 95, in wrapper
    with gzip.open(filepath, "rb") as file:
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/gzip.py", line 53, in open
    binary_file = GzipFile(filename, gz_mode, compresslevel)
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/gzip.py", line 163, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
FileNotFoundError: [Errno 2] No such file or directory: 'cache/trans_Q/1.pkl.gz'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/convolution.py", line 11, in __init__
    self.kernel = SE3Kernel(Rs_in, Rs_out, size, radial_window=radial_window, dyn_iso=dyn_iso, verbose=verbose)
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 315, in __init__
    basis = cube_basis_kernels(size, l_in, l_out, radial_window)  # [beta, i, j, x, y, z]
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 165, in cube_basis_kernels
    basis = radial_window(*_sample_cube(size, order_in, order_out))
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 135, in _sample_cube
    Q_J = _basis_transformation_Q_J(J, order_in, order_out)  # [m_out * m_in, m]
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/util/cache_file.py", line 100, in wrapper
    result = func(*args, **kwargs)
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 78, in _basis_transformation_Q_J
    null_space = get_matrices_kernel([_sylvester_submatrix(J, a, b, c) for a, b, c in random_angles])
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 78, in <listcomp>
    null_space = get_matrices_kernel([_sylvester_submatrix(J, a, b, c) for a, b, c in random_angles])
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 66, in _sylvester_submatrix
    R_tensor = _R_tensor(a, b, c)  # [m_out * m_in, m_out * m_in]
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/kernel.py", line 62, in _R_tensor
    def _R_tensor(a, b, c): return kron(irr_repr(order_out, a, b, c), irr_repr(order_in, a, b, c))
  File "/home/yalong/yalong/project/groupy-cnn/se3cnn/se3cnn/SO3.py", line 81, in irr_repr
    from lie_learn.representations.SO3.wigner_d import wigner_D_matrix
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/site-packages/lie_learn/representations/SO3/wigner_d.py", line 4, in <module>
    from lie_learn.representations.SO3.pinchon_hoggan.pinchon_hoggan_dense import Jd, rot_mat
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/site-packages/lie_learn/representations/SO3/pinchon_hoggan/pinchon_hoggan_dense.py", line 11, in <module>
    Jd = np.load(os.path.join(os.path.dirname(__file__), 'J_dense_0-278.npy'), encoding='latin1')
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/site-packages/numpy/lib/npyio.py", line 421, in load
    pickle_kwargs=pickle_kwargs)
  File "/home/yalong/yalong/software/anaconda3/envs/pytorch-0.4.1/lib/python3.6/site-packages/numpy/lib/format.py", line 650, in read_array
    array = pickle.load(fp, **pickle_kwargs)
_pickle.UnpicklingError: pickle data was truncated
>>> 
---------------------------------

**Comment by mariogeiger** [comment]
Did your installation of `lie_learn`  properly download the file `J_dense_0-278.npy` ?

**Comment by dragonbook** [comment]
Thank you! I solved it by downloading it again.
