### ISSUE TITLE
Assert failure in kernel.py

### ISSUE THREAD

**Issue by lupoglaz** [mariogeiger/se3cnn#8]
When I run the following code:

```
import torch
from se3cnn import SE3Convolution
size = 32
scalar_field = torch.randn(1, 1, size, size, size)  # [batch, _, x, y, z]
Rs_in = [(1, 0)]  # 1 scalar field
Rs_out = [(1, 1)]  # 1 vector field
conv = SE3Convolution(Rs_in, Rs_out, size=5)
vector_field = conv(scalar_field)

```

I get assertion error:
```
[gd387@e1c-136 se3cnn]$ python simple_test.py 
compute 0.pkl.gz... save 0.pkl.gz... done
compute 0.pkl.gz... save 0.pkl.gz... done
Traceback (most recent call last):
  File "simple_test.py", line 10, in <module>
    conv = SE3Convolution(Rs_in, Rs_out, size=5)
  File "/home1/gd387/Projects/se3cnn/se3cnn/convolution.py", line 11, in __init__
    self.kernel = SE3Kernel(Rs_in, Rs_out, size, radial_window=radial_window, dyn_iso=dyn_iso, verbose=verbose)
  File "/home1/gd387/Projects/se3cnn/se3cnn/kernel.py", line 239, in __init__
    basis = cube_basis_kernels(size, l_in, l_out, radial_window)  # [beta, i, j, x, y, z]
  File "/home1/gd387/Projects/se3cnn/se3cnn/kernel.py", line 89, in cube_basis_kernels
    basis = radial_window(*_sample_cube(size, order_in, order_out))
  File "/home1/gd387/Projects/se3cnn/se3cnn/kernel.py", line 74, in _sample_cube
    assert torch.allclose(tmp, K_J)
AssertionError
```

System: python 3.7.1 anaconda, lie_learn compiled and installed without problems, se3cnn installed, pytorch 1.0 cuda10

**Comment by lupoglaz** [comment]
Also a note: 
This assertion failure occured only on the cluster, my local server does not have such a problem. If you need any details on the configuration of both I will be happy to provide it.

**Comment by mariogeiger** [comment]
The problem was that 
```python
(xyz.norm(2, -1) == 0).nonzero().numel()
```
gives `0` when `xyz.size() = [3]` (and not `xyz.size() = [something, 3]`).
I fixed it by adding a `view(-1, 3)`

```python
(xyz.view(-1, 3).norm(2, -1) == 0).nonzero().numel()
```

This kind of border behaviors might behave differently according to he version of `pytorch`

**Comment by mariogeiger** [comment]
Oh, remove the corrupted cache!
`rm -r cache`
